extends Node2D

enum TILE_TYPES {
	TILE_INVALID_TILE = -1
	TILE_WATER_SHALLOW = 16,
	TILE_WATER_SURFACE = 19,
	TILE_WATER_BASE = 20,
	TILE_BREAKABLE_TYPE1 = 21,
	TILE_BREAKABLE_TYPE1_ANI = 22,
	TILE_BREAKABLE_TYPE2 = 23,
	TILE_BREAKABLE_TYPE2_ANI = 24
}
